import client from 'prom-client';

export const inputTokens = new client.Counter({
  name: 'llm_input_tokens_total',
  help: 'Total number of input tokens processed by LLMConversation',
});

export const outputTokens = new client.Counter({
  name: 'llm_output_tokens_total',
  help: 'Total number of output tokens generated by LLMConversation',
});

export { client as prom_metrics }; 